// <auto-generated />
using System;
using Egyptian_eInvoicing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Egyptian_eInvoicing.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119122934_FinalCleanSetup")]
    partial class FinalCleanSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentTypeVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExtraDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IssuerId")
                        .HasColumnType("int");

                    b.Property<int>("IssureId")
                        .HasColumnType("int");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiverId1")
                        .HasColumnType("int");

                    b.Property<string>("TaxpayerActivityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalItemsDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSalesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IssuerId");

                    b.HasIndex("IssureId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("ReceiverId1");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Lines.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceLineId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceLineId")
                        .IsUnique();

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Lines.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ItemsDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalesTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTaxableFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValueDifference")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("InvoiceLine");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Lines.UnitValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountEGP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrencyExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencySold")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceLineId")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceLineId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceLineId");

                    b.HasIndex("InvoiceLineId1")
                        .IsUnique()
                        .HasFilter("[InvoiceLineId1] IS NOT NULL");

                    b.ToTable("UnitValue");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Structures.Issuer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Issuer");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Structures.IssuerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IssuerAddress");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Structures.Receiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Receiver");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Structures.ReceiverAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReceiverAddress");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Tax.TaxTotal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentId1")
                        .HasColumnType("int");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentId1");

                    b.ToTable("TaxTotal");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Tax.TaxableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceLineId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceLineId");

                    b.ToTable("TaxableItem");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Document", b =>
                {
                    b.HasOne("Egyptian_eInvoicing.Models.Structures.Issuer", null)
                        .WithMany("Document")
                        .HasForeignKey("IssuerId");

                    b.HasOne("Egyptian_eInvoicing.Models.Structures.Issuer", "Issuer")
                        .WithMany()
                        .HasForeignKey("IssureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egyptian_eInvoicing.Models.Structures.Receiver", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Egyptian_eInvoicing.Models.Structures.Receiver", null)
                        .WithMany("Documents")
                        .HasForeignKey("ReceiverId1");

                    b.Navigation("Issuer");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Lines.Discount", b =>
                {
                    b.HasOne("Egyptian_eInvoicing.Models.Lines.InvoiceLine", "InvoiceLine")
                        .WithOne("Discount")
                        .HasForeignKey("Egyptian_eInvoicing.Models.Lines.Discount", "InvoiceLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceLine");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Lines.InvoiceLine", b =>
                {
                    b.HasOne("Egyptian_eInvoicing.Models.Document", "Document")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Lines.UnitValue", b =>
                {
                    b.HasOne("Egyptian_eInvoicing.Models.Lines.InvoiceLine", "InvoiceLine")
                        .WithMany()
                        .HasForeignKey("InvoiceLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egyptian_eInvoicing.Models.Lines.InvoiceLine", null)
                        .WithOne("UnitValue")
                        .HasForeignKey("Egyptian_eInvoicing.Models.Lines.UnitValue", "InvoiceLineId1");

                    b.Navigation("InvoiceLine");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Structures.Issuer", b =>
                {
                    b.HasOne("Egyptian_eInvoicing.Models.Structures.IssuerAddress", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Structures.Receiver", b =>
                {
                    b.HasOne("Egyptian_eInvoicing.Models.Structures.ReceiverAddress", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Tax.TaxTotal", b =>
                {
                    b.HasOne("Egyptian_eInvoicing.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egyptian_eInvoicing.Models.Document", null)
                        .WithMany("TaxTotals")
                        .HasForeignKey("DocumentId1");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Tax.TaxableItem", b =>
                {
                    b.HasOne("Egyptian_eInvoicing.Models.Lines.InvoiceLine", "InvoiceLine")
                        .WithMany("TaxableItems")
                        .HasForeignKey("InvoiceLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceLine");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Document", b =>
                {
                    b.Navigation("InvoiceLines");

                    b.Navigation("TaxTotals");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Lines.InvoiceLine", b =>
                {
                    b.Navigation("Discount")
                        .IsRequired();

                    b.Navigation("TaxableItems");

                    b.Navigation("UnitValue")
                        .IsRequired();
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Structures.Issuer", b =>
                {
                    b.Navigation("Document");
                });

            modelBuilder.Entity("Egyptian_eInvoicing.Models.Structures.Receiver", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
